CREATE TABLE IF NOT EXISTS products (
  `name` VARCHAR(255) NOT NULL,
  `image` VARCHAR(255) NOT NULL,
  `price` VARCHAR(255) NOT NULL
  `quantity` VARCHAR(255) NOT NULL
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  
  PRIMARY KEY (id) 
);