CREATE TABLE IF NOT EXISTS `order_items` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `productId` INT UNSIGNED NOT NULL,
  `orderId` INT UNSIGNED NOT NULL,
  `quantity` INT NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY (id)
  FOREIGN KEY (productId) REFERENCES products(id) 
  FOREIGN KEY (orderId) REFERENCES orders(id) 
);